name: Mark stale issues and pull requests
# https://github.com/actions/stale
on:
  schedule:
  - cron: "21 4 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        stale-issue-message: 'This issue has become stale and will be closed automatically within 7 days. Comment on the issue to keep it alive.'
        stale-pr-message: 'This pull request has become stale and will be closed automatically within 7 days. Comment on the PR to keep it alive.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 90
        days-before-issue-close: 7
        days-before-pr-close: 7